CREATE INDEX CUST_LN_FN ON CUSTOMERS (LAST_NAME, FIRST_NAME);

ALTER TABLE ORDERS
    MODIFY PARTITION BY RANGE (order_date)
        INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
        (PARTITION orders_init VALUES LESS THAN (DATE'2020-01-01'));
ALTER TABLE ORDER_ITEMS
    MODIFY PARTITION BY REFERENCE(ORDI_ORD_FK);


CREATE INDEX ADR_ZI_CI ON ADDRESSES (CITY, ZIP_CODE);

