--------------------------------------------------------------------------------
-- Primary Key Constraints
--------------------------------------------------------------------------------
ALTER TABLE COUNTRIES ADD CONSTRAINT CTR_PK PRIMARY KEY (CODE);
ALTER TABLE ADR_TYPES ADD CONSTRAINT ATP_PK PRIMARY KEY (ADR_TYPE);
ALTER TABLE CUSTOMERS ADD CONSTRAINT CUST_PK PRIMARY KEY (ID);
ALTER TABLE ADDRESSES ADD CONSTRAINT ADR_PK PRIMARY KEY (ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT PROD_PK PRIMARY KEY (ID);
ALTER TABLE ORDERS ADD CONSTRAINT ORD_PK PRIMARY KEY (ID);
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT ORDI_PK PRIMARY KEY (ID);

--------------------------------------------------------------------------------
-- Unique Constraints
--------------------------------------------------------------------------------
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT ORDI_UK UNIQUE(ORDER_ID, LINE_NO);

--------------------------------------------------------------------------------
-- Foreign Key Constraints
--------------------------------------------------------------------------------
ALTER TABLE ADDRESSES ADD CONSTRAINT ADR_CTR_FK FOREIGN KEY (CTR_CODE) REFERENCES COUNTRIES;
ALTER TABLE ADDRESSES ADD CONSTRAINT ADR_ATP_FK FOREIGN KEY (ADR_TYPE) REFERENCES ADR_TYPES;
ALTER TABLE ADDRESSES ADD CONSTRAINT ADR_CUST_FK FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS;
ALTER TABLE ORDERS ADD CONSTRAINT ORD_CUST_FK FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS;
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT ORDI_ORD_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS;
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT ORDI_PROD_FK FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS;

--------------------------------------------------------------------------------
-- Adjust Identity Columns
--------------------------------------------------------------------------------
ALTER TABLE CUSTOMERS MODIFY (ID GENERATED BY DEFAULT AS IDENTITY START WITH 20000);
ALTER TABLE ADDRESSES MODIFY (ID GENERATED BY DEFAULT AS IDENTITY START WITH 25000);
ALTER TABLE PRODUCTS MODIFY (ID GENERATED BY DEFAULT AS IDENTITY START WITH 100);
ALTER TABLE ORDERS MODIFY (ID GENERATED BY DEFAULT AS IDENTITY START WITH 2000000);
ALTER TABLE ORDER_ITEMS MODIFY (ID GENERATED BY DEFAULT AS IDENTITY START WITH 10000000);

--------------------------------------------------------------------------------
-- Gather Statistics
--------------------------------------------------------------------------------
BEGIN
   dbms_stats.gather_schema_stats
      (ownname => USER
      ,method_opt => 'FOR ALL COLUMNS SIZE SKEWONLY'
      ,no_invalidate => FALSE);
END;
/

