--------------------------------------------------------------------------------
-- Table COUNTRIES
--------------------------------------------------------------------------------
CREATE TABLE COUNTRIES
( CODE VARCHAR2(2 BYTE) NOT NULL
, NAME VARCHAR2(100 BYTE) NOT NULL
);

--------------------------------------------------------------------------------
-- Table ADR_TYPES
--------------------------------------------------------------------------------
CREATE TABLE ADR_TYPES
( ADR_TYPE VARCHAR2(2 BYTE) NOT NULL
, LABEL VARCHAR2(20) NOT NULL
);

--------------------------------------------------------------------------------
-- Table CUSTOMERS
--------------------------------------------------------------------------------
CREATE TABLE CUSTOMERS
( ID NUMBER(8) GENERATED BY DEFAULT AS IDENTITY NOT NULL 
, FIRST_NAME VARCHAR2(30 BYTE) NOT NULL
, LAST_NAME VARCHAR2(30 BYTE) NOT NULL
, DATE_OF_BIRTH DATE NOT NULL
, TITLE VARCHAR2(10 BYTE)
, GENDER VARCHAR2(1 BYTE)
, MARITAL_STATUS VARCHAR2(10 BYTE)
, MEMBER_FLAG VARCHAR2(1 BYTE)
, ACTIVE_FLAG VARCHAR2(1 BYTE)
, EMAIL_ADDRESS VARCHAR2(100 BYTE)
, LANGUAGE_CODE VARCHAR2(2 BYTE)
);

--------------------------------------------------------------------------------
-- Table ADDRESSES
--------------------------------------------------------------------------------
CREATE TABLE ADDRESSES
( ID NUMBER(8) GENERATED BY DEFAULT AS IDENTITY NOT NULL
, CUST_ID NUMBER(8) NOT NULL
, ADR_TYPE VARCHAR2(2 BYTE) NOT NULL
, STREET VARCHAR2(40 BYTE)
, STREET_NO VARCHAR2(10 BYTE)
, ZIP_CODE VARCHAR2(10 BYTE) NOT NULL
, CITY VARCHAR2(40 BYTE) NOT NULL
, CTR_CODE VARCHAR2(2 BYTE) NOT NULL
);

--------------------------------------------------------------------------------
-- Table PRODUCTS
--------------------------------------------------------------------------------
CREATE TABLE PRODUCTS
( ID NUMBER(8) GENERATED BY DEFAULT AS IDENTITY NOT NULL
, PROD_NAME	VARCHAR2(50 BYTE) NOT NULL
, PROD_DESC	VARCHAR2(4000 BYTE) NOT NULL
, PROD_CATEGORY	VARCHAR2(50 BYTE) NOT NULL
, SUPPLIER_ID	NUMBER(8)
, NUM_ON_STOCK	NUMBER(5)
, LIST_PRICE	NUMBER(8,2)
, MIN_PRICE	NUMBER(8,2)
);

--------------------------------------------------------------------------------
-- Table ORDERS
--------------------------------------------------------------------------------
CREATE TABLE ORDERS
( ID NUMBER(8) GENERATED BY DEFAULT AS IDENTITY NOT NULL
, CUST_ID NUMBER(8) NOT NULL
, ORDER_DATE DATE NOT NULL
);

--------------------------------------------------------------------------------
-- Table ORDER_ITEMS
--------------------------------------------------------------------------------
CREATE TABLE ORDER_ITEMS
( ID NUMBER(8) GENERATED BY DEFAULT AS IDENTITY NOT NULL
, ORDER_ID NUMBER(8) NOT NULL
, LINE_NO NUMBER(2) NOT NULL
, PROD_ID NUMBER(8) NOT NULL
, DELIVERY_DATE DATE
, QUANTITY NUMBER(3) NOT NULL
, PRICE_PER_UNIT NUMBER(8,2) NOT NULL
);
