-- USER dem TABLESPACE hinzufügen - mit dem Admin ausführen
-- ALTER USER BIANCA QUOTA UNLIMITED on DBARC3_TS;
-- ALTER USER DANIJEL QUOTA UNLIMITED on DBARC3_TS;

-- ALTER USER HUGENTOBLER QUOTA UNLIMITED on DBARC3_TS;
-- ALTER USER SONDEREGGER QUOTA UNLIMITED on DBARC3_TS;
-- ALTER USER SCHMIDT QUOTA UNLIMITED on DBARC3_TS;
-- ALTER USER NELSON QUOTA UNLIMITED on DBARC3_TS;
-- ALTER USER JASON QUOTA UNLIMITED on DBARC3_TS;
-- ALTER USER KELLY QUOTA UNLIMITED on DBARC3_TS;
-- ALTER USER DUPONT QUOTA UNLIMITED on DBARC3_TS;


-- Rollenkonzept für das Administrator-Team
CREATE ROLE DBARC3_ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADDRESSES TO DBARC3_ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CUSTOMERS TO DBARC3_ROLE_ADMIN;
GRANT SELECT ON ADR_TYPES TO DBARC3_ROLE_ADMIN;
GRANT SELECT ON COUNTRIES TO DBARC3_ROLE_ADMIN;

-- Hinzufügen der Rolle auf die Administratoren
GRANT DBARC3_ROLE_ADMIN TO DANIJEL;
GRANT DBARC3_ROLE_ADMIN TO BIANCA;


-- Rollenkonzept für das CRM-Team
-- Erstellen einer Tabelle um jedem Mitglied dieser Gruppe ihre Ländercodes zu zuweisen.
CREATE TABLE CRM_TEAM
(
    USERNAME varchar2(50),
    CTR_CODE varchar2(2)
); --todo primary key f¨r kombi

-- Hinzufügen jedes Mitgliedes mit seinen Ländercodes
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('HUGENTOBLER', 'CH');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('SONDEREGGER', 'CH');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('SCHMIDT', 'DE');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('NELSON', 'US');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('NELSON', 'CA');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('JASON', 'US');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('JASON', 'CA');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('KELLY', 'GB');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('KELLY', 'NZ');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('KELLY', 'SG');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('DUPONT', 'FR');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('DUPONT', 'IT');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('DUPONT', 'NL');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('DUPONT', 'DK');
INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('DUPONT', 'IS');
COMMIT;

-- VIEW erstellen um nur Userdaten zu sehen, welche den Ländercode des users haben.
CREATE OR REPLACE VIEW DBARC3_VIEW_CRM AS
SELECT CUSTOMERS.FIRST_NAME,
       CUSTOMERS.LAST_NAME,
       CUSTOMERS.DATE_OF_BIRTH,
       CUSTOMERS.TITLE,
       CUSTOMERS.GENDER,
       CUSTOMERS.MARITAL_STATUS,
       CUSTOMERS.MEMBER_FLAG,
       CUSTOMERS.ACTIVE_FLAG,
       CUSTOMERS.EMAIL_ADDRESS,
       CUSTOMERS.LANGUAGE_CODE,
       ADR_TYPES.LABEL AS ADDRESS_TYPE,
       ADDRESSES.STREET,
       ADDRESSES.STREET_NO,
       ADDRESSES.ZIP_CODE,
       ADDRESSES.CITY,
       COUNTRIES.NAME AS COUNTRY_NAME
FROM CUSTOMERS
         JOIN ADDRESSES ON CUSTOMERS.ID = ADDRESSES.CUST_ID
         JOIN ADR_TYPES ON ADR_TYPES.ADR_TYPE = ADDRESSES.ADR_TYPE
         JOIN COUNTRIES ON ADDRESSES.CTR_CODE = COUNTRIES.CODE
WHERE CTR_CODE IN (SELECT CTR_CODE FROM CRM_TEAM WHERE USERNAME = USER);


-- Rolle für CRM-Mitglieder erstellen und Rechte für die DBARC3_VIEW_CRM hinzufügen.
CREATE ROLE DBARC3_ROLE_CRM;
GRANT SELECT ON DBARC3_VIEW_CRM TO DBARC3_ROLE_CRM;

-- Rolle DBARC3_VIEW_CRM allen CRM-Mitgliedern hinzufügen.
GRANT DBARC3_ROLE_CRM to HUGENTOBLER;
GRANT DBARC3_ROLE_CRM to SONDEREGGER;
GRANT DBARC3_ROLE_CRM to SCHMIDT;
GRANT DBARC3_ROLE_CRM to NELSON;
GRANT DBARC3_ROLE_CRM to JASON;
GRANT DBARC3_ROLE_CRM to KELLY;
GRANT DBARC3_ROLE_CRM to DUPONT;


-- View um nur Adressen des Types 'D' oder 'DP' in der Schweiz anzuzeigen.
CREATE OR REPLACE VIEW DBARC3_VIEW_PAECKLI AS
SELECT TITLE, FIRST_NAME, LAST_NAME, STREET, STREET_NO, ZIP_CODE, CITY
FROM CUSTOMERS
         JOIN ADDRESSES ON ADDRESSES.CUST_ID = CUSTOMERS.ID
WHERE ADDRESSES.CTR_CODE = 'CH'
  AND (ADDRESSES.ADR_TYPE = 'D' OR ADDRESSES.ADR_TYPE = 'DP');

-- Dem User PAECKLI die VIEW DBARC3_VIEW_PAECKLI hinzufügen.
GRANT SELECT ON DBARC3_VIEW_PAECKLI TO PAECKLI;








SELECT *
FROM DBA_USERS;

INSERT INTO CRM_TEAM (USERNAME, CTR_CODE)
VALUES ('DBARC3_USER', 'CH');

update CRM_TEAM
set CTR_CODE = 'NL'
where USERNAME = user;
truncate table CRM_TEAM;
-- T
SELECT *
FROM CUSTOMERS
         JOIN ADDRESSES on CUSTOMERS.ID = ADDRESSES.CUST_ID
         JOIN ADR_TYPES on ADR_TYPES.ADR_TYPE = ADDRESSES.ADR_TYPE
         JOIN COUNTRIES ON ADDRESSES.CTR_CODE = COUNTRIES.CODE
WHERE CTR_CODE IN (SELECT CTR_CODE FROM CRM_TEAM WHERE USERNAME = USER);




SELECT * FROM CUSTOMERS
         JOIN ADDRESSES on CUSTOMERS.ID = ADDRESSES.CUST_ID
         JOIN ADR_TYPES on ADR_TYPES.ADR_TYPE = ADDRESSES.ADR_TYPE
         JOIN COUNTRIES ON ADDRESSES.CTR_CODE = COUNTRIES.CODE
WHERE CTR_CODE IN (
SELECT CTR_CODE FROM CRM_TEAM WHERE USERNAME = 'BIANCA');